name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install Python dependencies
        run: pip install -r requirements.txt
      - name: Python lint
        run: flake8 src test
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install ESLint
        run: |
          npm init -y >/dev/null 2>&1
          npm install eslint >/dev/null 2>&1
      - name: JavaScript lint
        run: npx eslint src test --ext .js

  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install Python dependencies
        run: pip install -r requirements.txt
      - name: Python unit tests
        run: PYTHONPATH=src python test/unit/slurmdb_validation.test.py
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Node unit tests
        run: node test/unit/calculator.test.js

  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install Python dependencies
        run: pip install -r requirements.txt
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Run integration tests
        run: make check

  security-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install Python dependencies
        run: pip install -r requirements.txt
      - name: Run Bandit
        run: bandit -r src
